### ISSUE TITLE
Hello, trouble to ask, the data saved, then the last is a URL?

### ISSUE THREAD

**Issue by HotBitmapGG** [Even201314/MRichEditor#1]
because my side of the demand is the user after editing, the need to upload data to the server, hoping to answer, thank you。

**Comment by HotBitmapGG** [comment]
@Even201314

**Comment by Even201314** [comment]
Sorry for replying so late.I've already replied to your Gmail.Thx for your kind attention.

**Comment by HotBitmapGG** [comment]
我看了你的邮件，就是我想知道的是，这个编辑器是webView来实现的，那么如果说我编辑完了，我怎么获取到我编辑完的url呢，因为我编辑完了，想在用webView显示出来，不知道这个需求能实现吗

**Comment by ZJYZJY** [comment]
我在编辑完成之后，先调用RichEditorAction的refreshHtml方法，再调用了RichEditorCallback的getHtml方法，但是没有得到返回的html。但是第二次就得到了，不知道是什么原因。

**Comment by Even201314** [comment]
@HotBitmapGG 我刚加了个接口，在dev分支,应该可以实现类似的需求。
```java
                mRichEditorAction.insertImageData(imageItem.name,
                    encodeFileToBase64Binary(imageItem.path));
```

**Comment by Even201314** [comment]
@ZJYZJY 
这个是由于JS回调时间差导致的。
refreshHtml 时`StartTime: 1503478197166`，回调时`EndTime: 1503478197173`。
还没改，暂时可以用postDelayed(Runnable action, long delayMillis)延迟获取返回的html

**Comment by ZJYZJY** [comment]
@HotBitmapGG 我编译sample有些按钮没有像gif里那样实时变化，也是因为这个吗

**Comment by ZJYZJY** [comment]
7ms的差距。

**Comment by HotBitmapGG** [comment]
@Even201314 谢谢，可以用
