### ISSUE TITLE
你好  问一下  如何获取最终生成的东西以什么样的方式上传服务器？

### ISSUE THREAD

**Issue by yangxiansheng123** [Even201314/MRichEditor#13]

**Comment by Even201314** [comment]
@yangxiansheng123 可以获取到的是一段Html文本（"<p>Hello World</p>"）

**Comment by yangxiansheng123** [comment]
怎么获取最终的HTML代码？哪一个方法可以获取？

**Comment by yangxiansheng123** [comment]
获取到HTML文本  调用那个方法 可以保存在本地么？

**Comment by spoilerror** [comment]
可以参看webview的用法

**Comment by spoilerror** [comment]
insertHtml(string)设置webview内容，RichEditorCallback.OnGetHtmlListener onGetHtmlListener  中设置读取html方法或接口

**Comment by yangxiansheng123** [comment]
你好 ！如何更改标签<img> 宽度  style="width: 340px;     这个style 如何更改为 style="width: 100%;？？？
