### ISSUE TITLE
大牛你好 我想问一下 我应该怎么获取到html 

### ISSUE THREAD

**Issue by JonsonBob** [Even201314/MRichEditor#15]
如题 不知道有没有 生成一个库呢 就是在gradle直接添加的依赖  如果方便 可以加我QQ 1525089850

**Comment by Even201314** [comment]
@JonsonBob 不好意思，暂时没有生成一个库。本来只是打算写一个demo的。所以很多东西也没有完善，Fragment返回事件也没有做处理。这个月我再找些时间完善一下库子，再添加gradle依赖吧。现在写的太粗糙了，仅供参考。

Html获取方式如下: 由于回调有延迟，暂时做法是延迟获取Hml的值。
```java
        mRichEditorAction.getHtml(mRichEditorCallback);
        mWebView.postDelayed(new Runnable() {
            @Override public void run() {
                  //延迟获取到Html
                  String html =  mRichEditorCallback.getHtml();
            }
        }, 500);
```

**Comment by JonsonBob** [comment]
哇 很感谢您的回复  那个... 大牛 方便加个QQ(1525089850) 当然 如果不方便也没事的 主要是我怕以我的技术在使用这个demo的时候出问题 然后每次都要到github上来向您提问很不方便

**Comment by JonsonBob** [comment]
@Even201314 大神 我没有找到你的那个mRichEditorAction.getHtml(mRichEditorCallback); 而且我的只需要实现几个功能  所以我把自定义RichEditorCallback里面的方法都注释了 不知道这样有没有影响
