### ISSUE TITLE
又来麻烦了，在问一个问题

### ISSUE THREAD

**Issue by HotBitmapGG** [Even201314/MRichEditor#3]
就是有什么方法可以进入富文本编辑界面就直接弹出软键盘的吗，我用了N种弹出键盘的方法都无效，求助， @Even201314

**Comment by Even201314** [comment]
刚刚提交了一次。修复了insertHtml后光标位置的问题。至于弹出键盘，可以在Java层面实现的。

**Comment by HotBitmapGG** [comment]
@Even201314 感谢大兄弟，解决了，要延迟1s在弹出软键盘就好了
