### ISSUE TITLE
mRichEditorCallback.getHtml()返回为null

### ISSUE THREAD

**Issue by ZhangWei2008** [Even201314/MRichEditor#5]
mRichEditorCallback.getHtml()返回为null

**Comment by Even201314** [comment]
@ZhangWei2008
这个是由于JS回调时间差导致的。
refreshHtml 时StartTime: 1503478197166，回调时EndTime: 1503478197173。
还没改，暂时可以用postDelayed(Runnable action, long delayMillis)延迟获取返回的html
