### ISSUE TITLE
调用mRichEditorAction.insertHtml(html);并且refresh了却没有显示内容

### ISSUE THREAD

**Issue by SunGuangjie** [Even201314/MRichEditor#6]
想直接加载一段html格式的String字符串，但是没有任何效果。

**Comment by Even201314** [comment]
看看是否和Issue 1的情况一样？#1

**Comment by SunGuangjie** [comment]
我是想直接加载一段从网络获取的html，不是Issue 1中获取已编辑完成内容的html。也就是说调用了
`mRichEditorAction.insertHtml(html)`
却没有在WebView中显示内容。

**Comment by Even201314** [comment]
@SunGuangjie 我写错了，应该是issue #2

**Comment by SunGuangjie** [comment]
嗯，解决了。是 Issue2 #2 。
谢谢。🤝
