### ISSUE TITLE
如何控制内容是否可以编辑？

### ISSUE THREAD

**Issue by SunGuangjie** [Even201314/MRichEditor#7]
尝试把richEditor.html中的
`div id="summernote" contenteditable="true"></div>`
**contenteditable** 设置为false，但是加载出来的内容仍然可以编辑。有其他的方法吗？

**Comment by Even201314** [comment]
@SunGuangjie 试一下disable()方法

**Comment by SunGuangjie** [comment]
disable()可以的，但是背景会变暗。
这个**contenteditable**设置是做什么用的

**Comment by Even201314** [comment]
其实不设置也没关系。
我修改了一下样式，你试一下最新的[提交](https://github.com/Even201314/MRichEditor/commit/4d286e9ce773bd1ed32ddcaeffca97a77c6f1d81),看看有没有效果

**Comment by SunGuangjie** [comment]
可以了。多谢。
希望有机会为这个项目出点力。
